### ISSUE TITLE
The blue LED on the D1 is always on

### ISSUE THREAD

**Issue by arthurkok2** [kp-bit/xblinds#10]
Either this LED should be disabled, or a ability to configure it off.

**Comment by kp-bit** [comment]
Actually tried to put code in there to turn it off but the onboard LED is controlled by the D4 pin which is also used to control the stepper, so there's no way to turn it high and keep it there, unfortunately. Maybe some black tape is the best option...

**Comment by arthurkok2** [comment]
oh that is unfortunate. black tape is also my current solution.
