### ISSUE TITLE
Status topic should respond with "opening" or "closing" when blinds are opening or closing

### ISSUE THREAD

**Issue by arthurkok2** [kp-bit/xblinds#12]
To support state_opening and state_closing on the integration, the xblinds/window/status should respond with "opening" or "closing" when the blinds are opening or closing.

See [(https://www.home-assistant.io/integrations/cover.mqtt/)]

**Comment by kp-bit** [comment]
I've put it on my list for a future release (finalizing and testing the next one at the moment).

**Comment by kp-bit** [comment]
Actually turned out to be easy to implement and I think it's a great functionality, so it will go into v0.7... I'm aiming for "tilt" support in a later release...
