### ISSUE TITLE
Suggestion: use power supply from D1 Mini USB port?

### ISSUE THREAD

**Issue by MagaliDB** [kp-bit/xblinds#13]
Wouldn't it be easier to use the power supply from the D1 Mini USB port? I tested the assembled unit with the D1 Mini connected to my laptop with USB, and it seems to work just fine that way. I was able to control the unit.

**Comment by arthurkok2** [comment]
This is what I have done as well. I actually modified the STL and added a hole on the side for the USB port. A laptop USB port might not deliver enough current, better to switch to a 2A switching USB power supply.

**Comment by MagaliDB** [comment]
> This is what I have done as well. I actually modified the STL and added a hole on the side for the USB port. A laptop USB port might not deliver enough current, better to switch to a 2A switching USB power supply.

Could you upload the modified STL as a remix on thingiverse? Would love to use it, that way I don't have to use my soldering iron to burn a hole on the side haha

**Comment by arthurkok2** [comment]
> > This is what I have done as well. I actually modified the STL and added a hole on the side for the USB port. A laptop USB port might not deliver enough current, better to switch to a 2A switching USB power supply.
> 
> Could you upload the modified STL as a remix on thingiverse? Would love to use it, that way I don't have to use my soldering iron to burn a hole on the side haha

here you go! ~~https://www.thingiverse.com/thing:4832349~~ (removed, due to dangers, PM me if you still want it knowing the risks)

**Comment by kp-bit** [comment]
You can't pull enough current from the 5V pin when powering the D1 from USB to provide any kind of torque on the stepper, and you can damage the D1 from trying. So you can power the D1 with USB but you would need to feed 5-12V directly to the ULN2003 (shared ground) for it to work - so it would be much easier to just power both with a 5V source, thus my design...

**Comment by arthurkok2** [comment]
yea @kp-bit you might be right. I am reviewing the schematic - looks like there's a fuse and diode between the USB 5v and the 5V pin of the board.  So powering the motor through this method is definitely not idea as the fuse can blow.

![image](https://user-images.githubusercontent.com/5326296/115256974-b217b400-a0fd-11eb-819c-f0a4b879730a.png)

**Comment by kp-bit** [comment]
Not sure how accurate those data sheets are or if they fit all D1's, if there's a diode there, we shouldn't be able to power it via the 5V pin...

**Comment by arthurkok2** [comment]
you'll still be able to power the board thru the 5V pin as the "+5V" rail is common. the diode is there to prevent the 5V supplying voltage back through the USB's VBUS

**Comment by MagaliDB** [comment]
@kp-bit you're right, I didn't read the documentation correctly. I thought you meant not to power it over USB from the pc, totally misunderstood that haha 😅 English is not my native language. 
It does indeed not pull properly when powered on USB only, so today I soldered a 5V 2.5A PSU (didn't have anything lower then 2.5A) and it works great!
Sorry for my misunderstanding and thanks again for this wonderful project.

**Comment by kp-bit** [comment]
@MagaliDB, good to hear that it worked out for you - enjoy!
