### ISSUE TITLE
Stronger Motor

### ISSUE THREAD

**Issue by cima37** [kp-bit/xblinds#17]
A great project in advance! Is it possible to use a stronger engine? I wanted to automate external blinds with it. (In principle, the same system but only with a cord) The 5v engine is a little too weak for that, I guess. I'm building an attempted drive with a Nema17 stepper and an A4988 stepstick stepper driver.

**Comment by kp-bit** [comment]
Well, the casing for the unit is designed specifically for the 28BYJ-48 stepper to keep it as sleek and easy to blend in, as possible. The Nema17 is huge in comparison and would require a very large casing, so I think you'd be better off designing something from scratch...
