### ISSUE TITLE
Can't go from closed to half

### ISSUE THREAD

**Issue by Smallinger** [kp-bit/xblinds#19]
With the new version v0.7 i have a problem.

When I try to switch from the closed position to the half position, nothing moves.

But if I change to half position in the open or fully open state, then it works without any problems.

**Comment by kp-bit** [comment]
I know, it's fixed in v0.8 coming out tomorrow... Thanks!

**Comment by kp-bit** [comment]
@Smallinger, v0.8 has been published now... Enjoy!
