### ISSUE TITLE
MQTT closes on command then opens straight away

### ISSUE THREAD

**Issue by BadgerJed** [kp-bit/xblinds#24]
Hi thanks for the great project. I am using it on string operated vertical handing blinds that open horizontal across the window. It takes about 30 seconds for them to open. When I access it through the IP address they work fine. I have now set up MQTT control with home assistant and Mosquito. When I send the close command they close fine, pause for a few moments then open again. I notice the log shows I initiated the close command but not the open. There is also a time out between each line. This is my first attempt at using MQTT so I expect I'm missing something obvious. Do you know what setting I would need to change to stop this happening. Thanks!

**Comment by kp-bit** [comment]
In general it's best to use either MQTT or the web interface. Using them in combination may give you unwanted results. When using MQTT you should always use the retain flag which will make sure that the blinds know what the last command was. This command is not published to MQTT when buttons are pressed, only the current status. That means that MQTT can override the buttons is the ESP gets disconnected for some reason or the MQTT server repeats the command. Same "problem" when using a tactile button, so I'm looking into how to best solve that without having to rewrite too much code. Hope that sheds some light on your problem.
