### ISSUE TITLE
Suggestion: Ability to adjust (max) RPM

### ISSUE THREAD

**Issue by Electr1fying** [kp-bit/xblinds#29]
Hi!

I'm using your project for my roller blinds. With the help of Gears the 28BYJ-48 holds up pretty well, but not enough.

I noticed the Stepper skipping/struggling when at full speed, but it works fine when it is accelerating or is decelerating up to a certain point, so the speed/torque tradeoff is the issue here.

Can you implement a feature to adjust the max RPM the Stepper accelerates to? That way everyone can decide this tradeoff for themselves.

Thanks in advance!

**Comment by kp-bit** [comment]
Hi @Electr1fying, will see if it's easily implemented (both in code and gui). Expecting to find some time over Easter to release final version (with source).
