### ISSUE TITLE
[Feature request or something?] Auto detect end

### ISSUE THREAD

**Issue by jellewie** [kp-bit/xblinds#3]
Normally there is a way for getting a pulse if a stepper motor misses a step (it can't execute it).
I'm not sure if the board listed is capable of this without modifications, but here is my reasoning for a nice feature:

When a power loss or boot has occurred (or the user request a full open- or homing)
move motor so the blinds up, when it detects this 'step missed' pulse (for X times), stop and remember that position as 'fully open'

PS: I was just curious and found this on Thingiverse. I Still want to make something similar, so I'm just a bit scouting around. I also think that a version 2 can be way smaller with a custom PCB

**Comment by kp-bit** [comment]
Thanks for the comment - I like the idea but as far as I've researched the ULN2003 driver will not report back if the stepper is jammed. To avoid running past end-stops if power is lost, I'm saving the intended position to EEPROM before moving the stepper so unless power is cut when moving, it should know exactly where it is, when back online.
