### ISSUE TITLE
Release 1.0 gets stuck obtain IP Address

### ISSUE THREAD

**Issue by elmangi** [kp-bit/xblinds#35]
Hi, I've a problem with the release 1.0 with my nodemcu, when I connect my phone with the AP gets stuck obtain IP Address. I flashed the version 0.9 and works fine without problems.

**Comment by mitchdunc** [comment]
having the same issue. do we need to setup a static IP?

**Comment by kp-bit** [comment]
Hi guys, there's no DHCP server in the code, so if you can't connect to 4.3.2.1 after connecting to the AP, you will need to configure a static IP on your device. This has been tested countless times from an iPhone and works without setting anything.
