### ISSUE TITLE
MQTT HA Problem

### ISSUE THREAD

**Issue by raphhorn** [kp-bit/xblinds#37]
everytime Home assitant reboots i have to type in the Mqtt paswwort on the Web Interface of each blind then it works but its everytime

**Comment by kp-bit** [comment]
I need a little more information... Are you using the exact D1 mini listed in the BOM? Which MQTT broker are you using and is it updated? What version of HA? Have you tried reflashing the D1 with latest build?

**Comment by raphhorn** [comment]
yes exact D1 Mini as you linked

Mosquitto Broker as a ADD ON in HA (version:6.3.1)

HA: Home Assistant 2023.9.2
      Operating System 11.0

HA run on a Raspberry PI 3+

flashed 4x D1 mini with v1.0 multipel times


the issue is everytime on all 4 the same

**Comment by kp-bit** [comment]
Sounds like there's no "EEPROM" on your modules - do you have a normal ESP8266 to test with? I've had 4 D1's running in production for more than 2 years and never seen this issue. And if it was a general issue, I'd have heard about it before...

**Comment by raphhorn** [comment]
You think that the D1 Mini forgot the passwort because of power loss but the problems appears when i start HA new so the D1 Mini has constant power and until i restarts HA it works

**Comment by kp-bit** [comment]
What if you just restart the D1, after HA has restarted? Does it reconenct then?

**Comment by raphhorn** [comment]
> What if you just restart the D1, after HA has restarted? Does it reconenct then?

No it works only if i type in the mqtt passwort everything else is remebered

**Comment by kp-bit** [comment]
So the password is actually remembered, it's just not exposed in the textbox on the webpage (same on the wifi page). Could you try presssing "Reboot ESP" on the "Setup" page, instead of typing the password and see if it reconnects?

**Comment by raphhorn** [comment]
> So the password is actually remembered, it's just not exposed in the textbox on the webpage (same on the wifi page). Could you try presssing "Reboot ESP" on the "Setup" page, instead of typing the password and see if it reconnects?

Yeah i know that it is not exposed 
I tried alredy reboot the esp or unplug it for a couple seconds

**Comment by raphhorn** [comment]
Could this be a mqtt broker problem it only appears with xblinds but is there maybe a setting wrong

**Comment by kp-bit** [comment]
Possibly. I have experienced that Mosquitto needs an occasional restart with some HA versions, it seems to be behaving well with HA version 2023.10.3

**Comment by raphhorn** [comment]
I check all my setting and your Troubleshooting tipps and my mosquitto settings again and let you know if it still there

**Comment by raphhorn** [comment]
everytime the mosquitto broker restarts the problem appears and if i press reboot esp it works 

is there a way to restart it automaticly

**Comment by kp-bit** [comment]
It should restart eventually on lost communication with the broker (if detected properly). I saw something similar in HA 2021.11.x where I had to toggle power to the blinds, so you might want to make sure you're on the latest HA. Alternatively, you can play around with MQTT KeepAlive (line 470 in the code) if you're up for recompiling it. Don't think there's much I can do here, so will close the issue.
