### ISSUE TITLE
Problem with mqtt

### ISSUE THREAD

**Issue by szwarx** [kp-bit/xblinds#39]
Hello, I have a problem with mqtt configuration. I really like your project but I can't deal with it. In mqtt explorer only exposes xblinds/window/status but it does not change when I move the blinds through the website. After connecting to homeassistant, sending payload comments does not work, and additionally, after adding the code to configuration.yaml, the device does not appear as an entity. Please help

**Comment by kp-bit** [comment]
Hi @szwarx, you should be able to see an entity as e.g.: "cover.xblinds_window" in Developer Tools, if you've followed the guidance. If you don't see it, you may not have configured it properly. I have a separate mqtt.yaml file with a cover: section. 
If everything is configured correctly and the user you're logging on with from xlinds is allowed to publish to Mosquitto, you should see status messages when you listen to xblinds/# (Settings -> Devices & services -> MQTT -> Configure).
