### ISSUE TITLE
motor skips

### ISSUE THREAD

**Issue by sdebije** [kp-bit/xblinds#6]
Hi first of all Great design!
Printed and modifyed the pulley. all fits great.
But i have a problem.
The motor skips and stutters when trying to pull up the blind.
Is there any solution for that.
I already put wd40 on the blinds and they run realy smooth.
I use a 5v 2000 mah powersupply splitted to the motor control board and the esp8266.

I used the motor from the link to amazon.

Hope you can help me.

**Comment by weider1** [comment]
Hey,

Do you have a vertical blind?

Had the problem that the motor wasn't strong enough, the blind is 2 meters long. 
Had to use another motor like Nema 17 and tmd 2208 driver board

**Comment by sdebije** [comment]
I have Horizontal blinds

**Comment by kp-bit** [comment]
Oh, you want to pull up the blind and not just turn it? That stepper won't do that kind of pulling, you need a more powerful one.
