### ISSUE TITLE
Any recommendations for a more powerful motor 

### ISSUE THREAD

**Issue by 1-ben-1** [kp-bit/xblinds#8]
Hi, I have blinds that move up and down. Would you happen to recommend a more powerful motor to move the blind up and down? If I was to get another motor would it just work or would the code need to be written?

Thank you

Ben

**Comment by kp-bit** [comment]
The code is specifically written for the ULN2003 driver, so if you're looking to use a larger stepper and another driver, maybe something like Tasmota could be the solution for you...
